#!/usr/bin/env node
// Converts docs/TERMS.md and docs/PRIVACY.md into a single TypeScript module
// (backend/src/legal-content.ts) consumed by backend/src/legal.ts at request
// time. The Cloudflare Worker can't read files at runtime, so the legal copy
// has to be embedded into the bundle. Keep the markdown files as the canonical
// source — re-run this script after editing them.
//
// Run: node backend/scripts/build-legal.mjs

import { readFile, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { marked } from 'marked'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..', '..')

const files = [
  { md: resolve(repoRoot, 'docs', 'TERMS.md'),   constName: 'TERMS_HTML'   },
  { md: resolve(repoRoot, 'docs', 'PRIVACY.md'), constName: 'PRIVACY_HTML' },
]

const banner = `// AUTO-GENERATED by backend/scripts/build-legal.mjs.
// Source: docs/TERMS.md, docs/PRIVACY.md.
// Do not edit this file by hand — edit the markdown sources and re-run the
// script (npm run build:legal in backend/).
`

const blocks = []
for (const { md, constName } of files) {
  const source = await readFile(md, 'utf8')
  const html = marked.parse(source, { gfm: true, breaks: false })
  // Backtick-escape for safe template-literal embedding.
  const escaped = String(html).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
  blocks.push(`export const ${constName}: string = \`${escaped}\``)
}

const out = `${banner}\n${blocks.join('\n\n')}\n`
const outPath = resolve(repoRoot, 'backend', 'src', 'legal-content.ts')
await writeFile(outPath, out, 'utf8')
console.log(`[build-legal] Wrote ${outPath} (${out.length} bytes)`)
