export const DEFAULT_STATE = {
    _meta: { projectPath: null, createdAt: null, updatedAt: null },
    mode: 'fiction',
    pipeline: 'novel',
    subMode: null,
    bookDna: {},
    nfStages: {},
    stages: {},
    genre: {
        primaryGenre: null,
        subGenre: null,
        targetWordCount: 80000,
        tone: null,
        audience: null,
        genreVariant: 'standard',
    },
    premise: {
        rawLogline: null,
        conceptHook: null,
        seriesPotential: null,
        seriesContext: {
            isSeries: false,
            seriesTitle: null,
            bookCount: null,
            currentBookNumber: 1,
            overallArc: null,
            firstBookFocus: null,
        },
    },
    protagonist: {
        name: null, age: null, occupation: null, dailyLife: null,
        want: null, need: null, ghost: null, flaw: null, coreLie: null,
        arcDirection: null, voice: null,
    },
    characters: [],
    relationships: [],
    logline: {
        sentence: null, setup: null, incitingIncident: null,
        stakes: null, resolutionHint: null, antagonistQuestion: null,
    },
    beatSheet: {
        genreVariant: 'standard',
        beats: {
            beat01OpeningImage: { scene: null, image: null, notes: null },
            beat02Setup: { scene: null, themeStated: null, notes: null },
            beat03Catalyst: { scene: null, incitingIncident: null, notes: null },
            beat04Debate: { scene: null, debateQuestion: null, notes: null },
            beat05BreakIntoTwo: { scene: null, falseReality: null, threshold: null, notes: null },
            beat06BStory: { scene: null, bStoryIntro: null, themeConnection: null, notes: null },
            beat07FunAndGames: { scene: null, promiseOfPremise: null, toneParity: null, notes: null },
            beat08Midpoint: { scene: null, midpointType: null, flipOrReveal: null, stakesRaise: null, notes: null },
            beat09BadGuysCloseIn: { scene: null, pressures: null, notes: null },
            beat10AllIsLost: { scene: null, wallopMoment: null, darkNightOfSoul: null, whiffOfDeath: null, notes: null },
            beat11BlackMoment: { scene: null, defeatType: null, despair: null, whatMakesThemTry: null, notes: null },
            beat12Beat13: { scene: null, secondDoorway: null, forcedReexamination: null, notes: null },
            beat13Finale: { scene: null, climaxType: null, selfRevelation: null, newEquilibrium: null, notes: null },
            beat14FinalImage: { scene: null, contrastToOpening: null, notes: null },
            beat15EndCredits: { scene: null, reflection: null, notes: null },
        },
        overallNotes: null,
    },
    bStory: { character: null, premise: null, beats: {}, resolution: null, themeConnection: null },
    subplots: [],
    sceneOutline: { highLevel: [], approved: false, fleshedChapters: [] },
    plotThreads: [],
    chapterOutline: [],
    critique: {
        flaggedIssues: [], resolvedIssues: [],
        pacingAnalysis: null, characterConsistency: null, beatSheetValidation: null,
    },
    masterDoc: { generatedAt: null, markdown: null, wordCountEstimate: null },
    writing: { manuscriptPath: 'manuscript' },
};
export const STAGE_ORDER = [
    { index: 1, id: 'genre', name: 'Genre & Foundations', nextPrompt: 'genre' },
    { index: 2, id: 'premise', name: 'Story Seed & Premise', nextPrompt: 'premise' },
    { index: 3, id: 'protagonist', name: 'Protagonist Deep Dive', nextPrompt: 'protagonist' },
    { index: 4, id: 'characters', name: 'Supporting Cast', nextPrompt: 'characters' },
    { index: 5, id: 'relationships', name: 'Relationship Web', nextPrompt: 'relationships' },
    { index: 6, id: 'logline', name: 'Logline Refinement', nextPrompt: 'logline' },
    { index: 7, id: 'beatSheet', name: 'Beat Sheet', nextPrompt: 'beatSheet' },
    { index: 8, id: 'bStory', name: 'B Story', nextPrompt: 'bStory' },
    { index: 9, id: 'subplots', name: 'Subplots', nextPrompt: 'subplots' },
    { index: 10, id: 'sceneOutline', name: 'Scene Outline', nextPrompt: 'sceneOutline' },
    { index: 11, id: 'plotThreads', name: 'Plot Thread Registry', nextPrompt: 'plotThreads' },
    { index: 12, id: 'chapterOutline', name: 'Chapter Flesh-Out', nextPrompt: 'chapterOutline' },
    { index: 13, id: 'critique', name: 'Consistency & Critique', nextPrompt: 'critique' },
    { index: 14, id: 'masterDoc', name: 'Master Document', nextPrompt: 'masterDoc' },
];
export const STAGE_BY_ID = Object.fromEntries(STAGE_ORDER.map(s => [s.id, s]));
//# sourceMappingURL=project-state.js.map