// Doctor — cross-surface drift detection for novel projects.
//
// Three surfaces must stay aligned, or the project ends up in the state
// that triggered this file's creation (stages 12/13/14 with prose docs
// on disk but state.json stuck at stage 11):
//
//   1. state.json            — structured planning data
//   2. output/stages/<id>.md — per-stage human-readable record (auto-
//                               generated by `nw save`)
//   3. memory.jsonl          — durable memory log, pushed to odd-flow
//                               MCP via `nw memory sync`
//
// Plus `docs/` where writers sometimes manually land late-stage prose
// before realising it should have gone through `nw save`.
//
// The doctor is called by the /novel skill at every stage closure and
// at the start of every session. If it reports drift, the skill halts
// until the writer/AI fixes it — no more silent state divergence.

import { promises as fs } from 'fs';
import { resolve } from 'path';
import { STAGE_ORDER } from './state/project-state.js';
import { getMissingRequirements } from './state/transitions.js';
import { getSyncStatus } from './memory/sync.js';
import { compareManuscriptToPlan } from './manuscript/compare.js';
import { scanManuscriptNotes } from './manuscript/notes.js';

// Filenames in docs/ that historically correspond to late-stage output
// landing outside the `nw save` pipeline. Maps filename substring →
// stage id. Extend as new offenders show up.
const DOC_PATTERNS = [
  { match: /chapter[-_]flesh[-_]out/i, stageId: 'chapterOutline' },
  { match: /consistency[-_]critique|^critique/i, stageId: 'critique' },
  { match: /master[-_]document|^master\.md$/i, stageId: 'masterDoc' },
];

function stageCommitted(stageId, state) {
  // "Committed" is stricter than the transitions-model's "complete":
  //   - The usual requirements must pass (getMissingRequirements empty), AND
  //   - For the two last stages whose requirements are fields: [] but whose
  //     actual point IS to capture output, at least one content slot must
  //     be populated. This prevents the exact bug the doctor was built for:
  //     a 270-line critique.md on disk with state.critique = {} shouldn't
  //     look "committed" just because its requirement list is empty.
  if (getMissingRequirements(stageId, state).length > 0) return false;

  if (stageId === 'critique') {
    const c = state.critique || {};
    return !!(c.pacingAnalysis || c.characterConsistency || c.beatSheetValidation
           || (Array.isArray(c.flaggedIssues) && c.flaggedIssues.length > 0));
  }
  if (stageId === 'masterDoc') {
    return !!(state.masterDoc?.generatedAt || state.masterDoc?.markdown);
  }
  return true;
}

async function listDocsMarkdown(projectPath) {
  const dir = resolve(projectPath, 'docs');
  try {
    const entries = await fs.readdir(dir);
    return entries.filter(name => /\.md$/i.test(name));
  } catch {
    return [];
  }
}

async function fileExists(path) {
  try { await fs.stat(path); return true; } catch { return false; }
}

// Build a report object describing every drift finding. Caller formats
// for human or JSON output.
export async function runDoctor(state, projectPath = process.cwd()) {
  const findings = [];

  // ── Stage-level drift ─────────────────────────────────────────
  // For every stage, compare: does state say it's done? does the
  // auto-generated stage doc exist? do any docs/ files hint that it
  // was worked on but not saved?

  const docsFiles = await listDocsMarkdown(projectPath);
  const docsByStage = new Map();
  for (const name of docsFiles) {
    for (const { match, stageId } of DOC_PATTERNS) {
      if (match.test(name)) {
        if (!docsByStage.has(stageId)) docsByStage.set(stageId, []);
        docsByStage.get(stageId).push(`docs/${name}`);
      }
    }
  }

  for (const stage of STAGE_ORDER) {
    const isComplete = stageCommitted(stage.id, state);
    const stageDocPath = resolve(projectPath, 'output', 'stages', `${stage.id}.md`);
    const hasStageDoc = await fileExists(stageDocPath);
    const orphanDocs = docsByStage.get(stage.id) || [];

    if (!isComplete && (hasStageDoc || orphanDocs.length > 0)) {
      const hints = [];
      if (hasStageDoc) hints.push(`output/stages/${stage.id}.md`);
      hints.push(...orphanDocs);
      findings.push({
        type: 'orphan-artefact',
        severity: 'error',
        stageId: stage.id,
        stageName: stage.name,
        message: `Stage "${stage.name}" has artefact(s) on disk but state.json doesn't show it as complete.`,
        artefacts: hints,
        fix: `Reconstruct the structured data for this stage and run: nw save ${stage.id} '<json>' (or \`nw generate\` for masterDoc).`,
      });
    }
  }

  // ── Memory sync drift ─────────────────────────────────────────
  let memoryStatus = null;
  try {
    memoryStatus = await getSyncStatus();
    if (memoryStatus.pendingEntries > 0) {
      findings.push({
        type: 'memory-pending',
        severity: 'warning',
        message: `${memoryStatus.pendingEntries} memory entr${memoryStatus.pendingEntries === 1 ? 'y is' : 'ies are'} in the durable log but not yet pushed to odd-flow MCP.`,
        pendingEntries: memoryStatus.pendingEntries,
        fix: 'Run `nw memory sync`, push each entry via mcp__odd-flow__memory_store, then `nw memory mark-synced <ids...>`.',
      });
    }
  } catch (err) {
    findings.push({
      type: 'memory-unreadable',
      severity: 'warning',
      message: `Could not read memory sync status: ${err.message}`,
    });
  }

  // ── Stage.stages marker sanity ────────────────────────────────
  // If state.stages[<id>].completed is true but the requirements don't
  // pass, the completion marker is stale — flag it.
  if (state.stages) {
    for (const stage of STAGE_ORDER) {
      const marker = state.stages[stage.id];
      if (marker?.completed && !stageCommitted(stage.id, state)) {
        findings.push({
          type: 'stale-completion-marker',
          severity: 'warning',
          stageId: stage.id,
          stageName: stage.name,
          message: `state.stages.${stage.id}.completed = true, but the stage's data requirements aren't satisfied.`,
          fix: `Either re-save the stage with the missing fields, or clear the marker manually.`,
        });
      }
    }
  }

  // ── Manuscript-vs-plan drift ──────────────────────────────────
  // Fold the compare-report's per-chapter drift findings into the
  // doctor's output so a writer running `nw doctor` sees everything —
  // plan/memory drift AND draft-vs-plan drift — in one place.
  let manuscriptReport = null;
  try {
    manuscriptReport = await compareManuscriptToPlan(state, projectPath);
    for (const f of manuscriptReport.findings) {
      if (f.type === 'progress') continue;  // info-only, not drift
      findings.push({
        ...f,
        type: `manuscript-${f.type}`,
      });
    }
  } catch (err) {
    findings.push({
      type: 'manuscript-compare-failed',
      severity: 'warning',
      message: `Could not compare manuscript to plan: ${err.message}`,
    });
  }

  // ── Inline manuscript notes ───────────────────────────────────
  // Writers embed <bracketed TBDs> in their prose; surface the count so
  // the doctor flags unresolved research/questions that would otherwise
  // get lost between sessions. Info-level — the notes aren't "wrong",
  // they're work in progress.
  let notes = [];
  try {
    notes = await scanManuscriptNotes(projectPath, {
      manuscriptPath: state?.writing?.manuscriptPath || 'manuscript',
    });
    if (notes.length > 0) {
      findings.push({
        type: 'manuscript-pending-notes',
        severity: 'info',
        count: notes.length,
        message: `${notes.length} inline note${notes.length === 1 ? '' : 's'} awaiting resolution in the manuscript.`,
        fix: 'Run `nw manuscript notes` to list them, or ask the /novel skill to resolve them (web research, plan lookup, or writer decision).',
      });
    }
  } catch {
    // Non-fatal — if the manuscript dir is missing the compare step
    // already raised a warning above.
  }

  return {
    ok: findings.every(f => f.severity !== 'error'),
    drift: findings.length > 0,
    findings,
    memoryStatus,
    manuscriptReport,
    notesCount: notes.length,
  };
}

// Human-readable formatter for `nw doctor` console output.
export function formatDoctorReport(report) {
  const lines = [];
  if (!report.drift) {
    lines.push('no drift — state.json, output/, docs/, and memory are aligned.');
    return lines.join('\n');
  }

  const errors = report.findings.filter(f => f.severity === 'error');
  const warnings = report.findings.filter(f => f.severity === 'warning');

  if (errors.length > 0) {
    lines.push(`DRIFT: ${errors.length} error${errors.length === 1 ? '' : 's'}, ${warnings.length} warning${warnings.length === 1 ? '' : 's'}`);
  } else {
    lines.push(`${warnings.length} warning${warnings.length === 1 ? '' : 's'} — no hard drift`);
  }
  lines.push('');

  for (const f of report.findings) {
    const sigil = f.severity === 'error' ? '✗' : '⚠';
    lines.push(`${sigil} [${f.type}${f.stageId ? ':' + f.stageId : ''}] ${f.message}`);
    if (f.artefacts?.length) {
      f.artefacts.forEach(a => lines.push(`      ${a}`));
    }
    if (f.fix) {
      lines.push(`      fix: ${f.fix}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
