import * as vscode from 'vscode';
import { promises as fs } from 'fs';
import * as path from 'path';

// "Novel Writer: Open Preview" — opens the latest print-preview HTML
// produced by the compile pipeline inside a VS Code webview panel.
// Paged.js runs in the webview and paginates the book as the writer
// would see it on paper. No external browser needed.
//
// If no preview HTML exists (writer hasn't compiled yet), offer to
// run "Novel Writer: Compile to Print PDF" first — the compile
// produces the preview HTML as a side effect.

export async function openPreview(): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder) {
    vscode.window.showErrorMessage('Novel Writer: open a novel project folder first.');
    return;
  }

  const stateFile = vscode.Uri.joinPath(folder.uri, '.novel-writer', 'state.json');
  try {
    await vscode.workspace.fs.stat(stateFile);
  } catch {
    vscode.window.showErrorMessage(
      'Novel Writer: no .novel-writer/state.json found. Run `nw init` first.',
    );
    return;
  }

  const outputDir = vscode.Uri.joinPath(folder.uri, 'output', 'compiled');
  let previewPath = await findLatestPreview(outputDir.fsPath);

  if (!previewPath) {
    const choice = await vscode.window.showInformationMessage(
      'No preview found. Compile to Print PDF first to generate the preview?',
      'Compile Now',
      'Cancel',
    );
    if (choice !== 'Compile Now') return;

    await vscode.commands.executeCommand('novelWriter.compilePrintPdf');
    previewPath = await findLatestPreview(outputDir.fsPath);
    if (!previewPath) {
      vscode.window.showErrorMessage(
        'Compile finished but no preview HTML was produced. Check the Novel Writer output channel.',
      );
      return;
    }
  }

  const panel = vscode.window.createWebviewPanel(
    'novelWriter.preview',
    `Print Preview — ${path.basename(previewPath, '-print-preview.html')}`,
    vscode.ViewColumn.Beside,
    {
      enableScripts: true,
      retainContextWhenHidden: true,
      // Allow the webview to load resources from the compile output dir
      // (images, fonts, etc., if themes later reference them).
      localResourceRoots: [outputDir],
    },
  );

  const html = await fs.readFile(previewPath, 'utf-8');
  panel.webview.html = injectWebviewCsp(html);
}

// ── private helpers ────────────────────────────────────────────

async function findLatestPreview(dirPath: string): Promise<string | null> {
  try {
    const entries = await fs.readdir(dirPath);
    const previews = entries.filter(e => e.endsWith('-print-preview.html'));
    if (previews.length === 0) return null;

    // If multiple preview HTMLs exist (e.g. writer changed the book title
    // between compiles), pick the most recently modified.
    const withMtimes = await Promise.all(
      previews.map(async (name) => {
        const full = path.join(dirPath, name);
        const stat = await fs.stat(full);
        return { full, mtime: stat.mtime.getTime() };
      }),
    );
    withMtimes.sort((a, b) => b.mtime - a.mtime);
    return withMtimes[0].full;
  } catch {
    return null;
  }
}

// VS Code webviews with enableScripts apply a restrictive default CSP
// unless the HTML overrides it. The preview HTML uses an inline <script>
// (Paged.js polyfill) and inline <style> (theme CSS) — both need to be
// allowed explicitly. The content is generated by our compile pipeline,
// not user input, so 'unsafe-inline' is an acceptable trade-off here.
function injectWebviewCsp(html: string): string {
  const csp = [
    `default-src 'none'`,
    `style-src 'unsafe-inline'`,
    `script-src 'unsafe-inline'`,
    `img-src data: blob:`,
    `font-src data:`,
  ].join('; ');

  const meta = `<meta http-equiv="Content-Security-Policy" content="${csp}">`;
  // Insert right after <head> so it's parsed before any inline scripts run.
  return html.replace('<head>', `<head>\n  ${meta}`);
}
