// FIC-D.4 — Character arc matrix renderer.
//
// Derives `output/character-arc-matrix.md` from the normalized WritingPlan.
// One table per character. Skips characters with no arc data.
// Refreshed after saves to protagonist, characters, chapterOutline, beatSheet.

import * as fs from 'fs'
import * as path from 'path'
import type { WritingPlan } from '../state/writing-plan.js'

export interface ArcMatrixResult {
  outputPath: string
  characterCount: number
}

const BEAT_NAMES: Record<string, string> = {
  beat01OpeningImage: 'Opening Image',
  beat02Setup: 'Setup',
  beat03Catalyst: 'Catalyst',
  beat04Debate: 'Debate',
  beat05BreakIntoTwo: 'Break Into Two',
  beat06BStory: 'B Story',
  beat07FunAndGames: 'Fun and Games',
  beat08Midpoint: 'Midpoint',
  beat09BadGuysCloseIn: 'Bad Guys Close In',
  beat10AllIsLost: 'All Is Lost',
  beat11BlackMoment: 'Black Moment',
  beat12Beat13: 'Break Into Three',
  beat13Finale: 'Finale',
  beat14FinalImage: 'Final Image',
  beat15EndCredits: 'End Credits',
}

export function generateCharacterArcMatrix(plan: WritingPlan, projectDir: string): ArcMatrixResult {
  const outputDir = path.join(projectDir, 'output')
  fs.mkdirSync(outputDir, { recursive: true })

  const outputPath = path.join(outputDir, 'character-arc-matrix.md')
  const title = plan.title ?? 'Untitled'

  const lines: string[] = [
    `# Character Arc Matrix — ${title}`,
    '',
    `*Auto-generated by Storyline — edits will be overwritten on next save.*`,
    `*Generated: ${new Date().toISOString().split('T')[0]}*`,
    '',
  ]

  const rows = plan.arcMatrix?.characters ?? []

  if (rows.length === 0) {
    lines.push(
      '*No character arc data found. Complete the Protagonist and Characters stages to populate this matrix.*',
      '',
    )
  } else {
    for (const row of rows) {
      const roleLabel = row.role ?? null
      lines.push(`## ${row.characterName}${roleLabel ? ` *(${roleLabel})*` : ''}`, '')

      const arcFields: [string, string | null][] = [
        ['Want', row.want],
        ['Need', row.need],
        ['Lie', row.lie],
        ['Wound', row.wound],
      ]
      const hasInnerEngine = arcFields.some(([, v]) => v !== null)
      if (hasInnerEngine) {
        lines.push('| | |', '|---|---|')
        for (const [label, value] of arcFields) {
          if (value) lines.push(`| **${label}** | ${value} |`)
        }
        lines.push('')
      }

      if (row.chapterPresence.length > 0) {
        lines.push(`**Appears in:** ${row.chapterPresence.map(c => `Ch ${c}`).join(', ')}`, '')
      }

      if (row.beatPressure.length > 0) {
        const named = row.beatPressure.map(id => BEAT_NAMES[id] ?? id).join(', ')
        lines.push(`**Beat pressure:** ${named}`, '')
      }

      const storyArc: [string, string | null][] = [
        ['Midpoint shift', row.midpointShift],
        ['All Is Lost impact', row.allIsLostImpact],
        ['Finale choice', row.finaleChoice],
        ['Final state', row.finalState],
      ]
      const hasStoryArc = storyArc.some(([, v]) => v !== null)
      if (hasStoryArc) {
        lines.push('**Story arc:**', '')
        for (const [label, value] of storyArc) {
          if (value) lines.push(`- **${label}:** ${value}`)
        }
        lines.push('')
      }
    }
  }

  lines.push(
    '---',
    '*Storyline Arc Matrix — updated on every protagonist, character, chapter, or beat-sheet save.*',
  )

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

  return {
    outputPath,
    characterCount: rows.length,
  }
}
