// NF-12.2 — Claim/evidence ledger generator.
//
// Generates output/claim-evidence-ledger.md from WritingPlan.claims,
// grouped by chapter with a risk summary at the top.
// Refreshed on pa-evidence, pb-sourcing, and master-stage saves.

import * as fs from 'fs'
import * as path from 'path'
import type { WritingPlan, ClaimEvidenceItem } from '../state/writing-plan.js'

export interface ClaimLedgerResult {
  outputPath: string
  totalClaims: number
  unsupportedCount: number
  highRiskChapters: Array<{ chapterNumber: number; unsupportedCount: number }>
}

const STATUS_BADGE: Record<ClaimEvidenceItem['verificationState'], string> = {
  planned:  '⬜',
  sourced:  '🔵',
  captured: '🟡',
  verified: '🟢',
  cited:    '✅',
}

const RISK_BADGE: Record<ClaimEvidenceItem['risk'], string> = {
  high:   '🔴',
  medium: '🟠',
  low:    '🟢',
}

function renderClaim(c: ClaimEvidenceItem): string {
  const status = STATUS_BADGE[c.verificationState] ?? '⬜'
  const risk   = RISK_BADGE[c.risk] ?? '🔴'
  const src    = c.sources.length > 0 ? ` — *${c.sources.join(', ')}*` : ''
  const type   = c.evidenceType !== 'unparsed' ? ` [${c.evidenceType}]` : ''
  return `- ${status} ${risk} **${c.id}** ${c.claimText}${type}${src}`
}

export function generateClaimEvidenceLedger(plan: WritingPlan, projectDir: string): ClaimLedgerResult {
  const outputDir = path.join(projectDir, 'output')
  fs.mkdirSync(outputDir, { recursive: true })
  const outputPath = path.join(outputDir, 'claim-evidence-ledger.md')

  const title = plan.title ?? 'Untitled'
  const all = plan.claims
  const unsupported = all.filter(c => c.verificationState === 'planned' || c.verificationState === 'sourced')

  // Chapter risk: count high-risk unverified claims per chapter
  const chapterRisk = new Map<number, number>()
  for (const c of all) {
    if (c.risk === 'high' && c.chapterNumber != null &&
        c.verificationState !== 'verified' && c.verificationState !== 'cited') {
      chapterRisk.set(c.chapterNumber, (chapterRisk.get(c.chapterNumber) ?? 0) + 1)
    }
  }
  const highRiskChapters = [...chapterRisk.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([chapterNumber, unsupportedCount]) => ({ chapterNumber, unsupportedCount }))

  const lines: string[] = [
    `# Claim/Evidence Ledger — ${title}`,
    '',
    `*Auto-generated by Storyline — edits will be overwritten on next save.*`,
    `*Generated: ${new Date().toISOString().split('T')[0]}*`,
    `*${all.length} claim${all.length !== 1 ? 's' : ''} tracked · ${unsupported.length} unsupported · ${all.filter(c => c.risk === 'high').length} high-risk*`,
    '',
  ]

  // Risk overview table (top 5 chapters)
  if (highRiskChapters.length > 0) {
    lines.push('## Risk Overview', '')
    lines.push('| Chapter | High-Risk Claims |')
    lines.push('|---------|-----------------|')
    for (const { chapterNumber, unsupportedCount } of highRiskChapters.slice(0, 5)) {
      const chTitle = plan.nfChapters.find(c => c.number === chapterNumber)?.title ?? ''
      const label = chTitle ? `Ch ${chapterNumber} — ${chTitle}` : `Chapter ${chapterNumber}`
      lines.push(`| ${label} | ${unsupportedCount} |`)
    }
    lines.push('')
  }

  if (all.length === 0) {
    lines.push(
      '*No claims tracked yet. Complete the evidence or sourcing stage to populate this ledger.*',
      '',
    )
  } else {
    const byChapter = new Map<number, ClaimEvidenceItem[]>()
    const loose: ClaimEvidenceItem[] = []
    for (const c of all) {
      if (c.chapterNumber != null) {
        if (!byChapter.has(c.chapterNumber)) byChapter.set(c.chapterNumber, [])
        byChapter.get(c.chapterNumber)!.push(c)
      } else {
        loose.push(c)
      }
    }

    for (const chNum of [...byChapter.keys()].sort((a, b) => a - b)) {
      const items = byChapter.get(chNum)!
      const chTitle = plan.nfChapters.find(c => c.number === chNum)?.title ?? null
      const heading = chTitle ? `Chapter ${chNum} — ${chTitle}` : `Chapter ${chNum}`
      lines.push(`## ${heading}`, '')
      for (const c of items) lines.push(renderClaim(c))
      lines.push('')
    }

    if (loose.length > 0) {
      lines.push('## General Claims', '')
      for (const c of loose) lines.push(renderClaim(c))
      lines.push('')
    }
  }

  lines.push(
    '---',
    '**Status:** ⬜ planned · 🔵 sourced · 🟡 captured · 🟢 verified · ✅ cited  ',
    '**Risk:** 🔴 high · 🟠 medium · 🟢 low',
    '*Storyline Claim/Evidence Ledger — updated on every evidence or sourcing stage save.*',
  )

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

  return { outputPath, totalClaims: all.length, unsupportedCount: unsupported.length, highRiskChapters }
}
