// NF-13.2 — Figure registry renderer.
//
// Generates output/figure-registry.md from WritingPlan.figures,
// grouped by chapter with a type-summary table at the top.
// Refreshed after pa-chapters / pb-chapters / pc-lessons saves.

import * as fs from 'fs'
import * as path from 'path'
import type { WritingPlan, FigurePlanItem } from '../state/writing-plan.js'

export interface FigureRegistryResult {
  outputPath: string
  totalFigures: number
  producedCount: number
}

const STATUS_BADGE: Record<FigurePlanItem['status'], string> = {
  planned:    '⬜',
  generating: '⏳',
  produced:   '🟡',
  accepted:   '✅',
  rejected:   '🔴',
}

function renderFigure(f: FigurePlanItem): string {
  const badge = STATUS_BADGE[f.status] ?? '⬜'
  const sec = f.sectionTitle ? ` · *§ ${f.sectionTitle}*` : ''
  const cap = f.caption ? `  \n  *Caption: ${f.caption}*` : ''
  const alt = f.altText ? `  \n  *Alt: ${f.altText}*` : ''
  const asset = f.producedAssetPath ? `  \n  *Asset: \`${f.producedAssetPath}\`*` : ''
  return `- ${badge} **${f.id}** \`${f.type}\` — ${f.purpose}${sec}${cap}${alt}${asset}`
}

export function generateFigureRegistry(plan: WritingPlan, projectDir: string): FigureRegistryResult {
  const outputDir = path.join(projectDir, 'output')
  fs.mkdirSync(outputDir, { recursive: true })
  const outputPath = path.join(outputDir, 'figure-registry.md')

  const title = plan.title ?? 'Untitled'
  const all = plan.figures
  const produced = all.filter(f => f.status === 'produced' || f.status === 'accepted')

  // Type summary table
  const byType = new Map<string, number>()
  for (const f of all) byType.set(f.type, (byType.get(f.type) ?? 0) + 1)

  const lines: string[] = [
    `# Figure Registry — ${title}`,
    '',
    `*Auto-generated by Storyline — edits will be overwritten on next save.*`,
    `*Generated: ${new Date().toISOString().split('T')[0]}*`,
    `*${all.length} figure${all.length !== 1 ? 's' : ''} planned · ${produced.length} produced or accepted*`,
    '',
  ]

  if (byType.size > 0) {
    lines.push('## Figures by Type', '')
    lines.push('| Type | Count |')
    lines.push('|------|-------|')
    for (const [type, count] of [...byType.entries()].sort()) {
      lines.push(`| ${type} | ${count} |`)
    }
    lines.push('')
  }

  if (all.length === 0) {
    lines.push(
      '*No figures declared yet. Add a `figures` array to any chapter in the chapter-plan stage.*',
      '',
    )
  } else {
    const byChapter = new Map<number, FigurePlanItem[]>()
    const loose: FigurePlanItem[] = []
    for (const f of all) {
      if (f.chapterNumber != null) {
        if (!byChapter.has(f.chapterNumber)) byChapter.set(f.chapterNumber, [])
        byChapter.get(f.chapterNumber)!.push(f)
      } else {
        loose.push(f)
      }
    }

    for (const chNum of [...byChapter.keys()].sort((a, b) => a - b)) {
      const items = byChapter.get(chNum)!
      const chTitle = plan.nfChapters.find(c => c.number === chNum)?.title
        ?? plan.fictionChapters.find(c => c.chapterNumber === chNum)?.chapterTitle
        ?? null
      const heading = chTitle ? `Chapter ${chNum} — ${chTitle}` : `Chapter ${chNum}`
      lines.push(`## ${heading}`, '')
      for (const f of items) lines.push(renderFigure(f))
      lines.push('')
    }

    if (loose.length > 0) {
      lines.push('## General Figures', '')
      for (const f of loose) lines.push(renderFigure(f))
      lines.push('')
    }
  }

  lines.push(
    '---',
    '**Status:** ⬜ planned · ⏳ generating · 🟡 produced · ✅ accepted · 🔴 rejected',
    '*Storyline Figure Registry — updated on every chapter-plan save.*',
  )

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

  return { outputPath, totalFigures: all.length, producedCount: produced.length }
}
