// Master Document Generator — outputs the complete planning document as markdown
import * as fs from 'fs'
import * as fsPromises from 'fs/promises'
import * as path from 'path'
import type { ProjectState } from '../state/project-state.js'

export interface MasterDocResult {
  path: string
  wordCount: number
  chapterCount: number
  beatCount: number
  threadCount: number
}

export async function generateMasterDocument(
  state: ProjectState,
  projectPath: string,
): Promise<MasterDocResult> {
  const outputDir = path.resolve(projectPath, 'output')
  fs.mkdirSync(outputDir, { recursive: true })

  const genre = state.genre || ({} as ProjectState['genre'])
  const protagonist = state.protagonist || ({} as ProjectState['protagonist'])
  const logline = (state.logline || {}) as Record<string, string | null>
  const beatSheet = state.beatSheet || ({} as ProjectState['beatSheet'])
  const bStory = (state.bStory || {}) as Record<string, unknown>
  const subplots = (state.subplots || []) as Array<{
    name: string
    character?: string
    purpose?: string
    premise?: string
    beats?: { setup?: string; complication?: string; resolution?: string }
  }>
  const chapters = (state.chapterOutline || []) as Array<{
    chapterNumber: number
    chapterTitle?: string
    beat?: string
    scenes: Array<{
      sceneNumber: number
      location?: string
      timeOfDay?: string
      pov?: string
      summary?: string
      purpose?: string
      conflict?: string
      whatChanges?: string
      beats?: string
    }>
  }>
  const threads = (state.plotThreads || []) as Array<{
    name: string
    type?: string
    status?: string
    resolutionPlan?: string
  }>

  let wordCount = 0

  const count = (text: string | null | undefined): void => {
    if (text) wordCount += text.split(' ').length
  }

  const md: string[] = []

  // ─── TITLE PAGE ────────────────────────────────────────────────
  md.push('# NOVEL PLANNING DOCUMENT\n')
  md.push(`**Title:** ${(state._meta as Record<string, unknown>)?.projectTitle as string || 'Untitled'}\n`)
  md.push(`**Genre:** ${genre.primaryGenre}${genre.subGenre ? ` / ${genre.subGenre}` : ''}\n`)
  md.push(`**Tone:** ${genre.tone || 'Not set'}\n`)
  md.push(`**Target:** ${genre.targetWordCount?.toLocaleString() || '80,000'} words\n`)
  md.push(`**Variant:** ${beatSheet.genreVariant || 'standard'}\n`)
  if (state.premise?.seriesContext?.isSeries) {
    md.push(`**Series:** ${state.premise.seriesContext.seriesTitle} (Book ${state.premise.seriesContext.currentBookNumber || 1})\n`)
  }
  md.push(`\n*Generated by Storyline — Save the Cat Planning Harness*\n`)
  md.push('---\n')

  // ─── LOGLINE ───────────────────────────────────────────────────
  if (logline.sentence) {
    md.push('## LOGLINE\n')
    md.push(`> ${logline.sentence}\n`)
    md.push('\n')
    count(logline.sentence)
  }

  // ─── GENRE & FOUNDATIONS ──────────────────────────────────────
  md.push('## GENRE & FOUNDATIONS\n')
  md.push(`| Field | Value |\n`)
  md.push(`|-------|-------|\n`)
  md.push(`| Primary Genre | ${genre.primaryGenre || '-'} |\n`)
  md.push(`| Sub-Genre | ${genre.subGenre || '-'} |\n`)
  md.push(`| Audience | ${genre.audience || '-'} |\n`)
  md.push(`| Tone | ${genre.tone || '-'} |\n`)
  md.push(`| Target Word Count | ${genre.targetWordCount?.toLocaleString() || '-'} |\n`)
  md.push(`| Genre Variant | ${beatSheet.genreVariant || 'standard'} |\n`)
  md.push('\n')

  // ─── PREMISE ───────────────────────────────────────────────────
  if (state.premise?.rawLogline) {
    md.push('## STORY SEED\n')
    md.push(`${state.premise.rawLogline}\n\n`)
    if (state.premise.conceptHook) {
      md.push(`**Hook:** ${state.premise.conceptHook}\n\n`)
    }
    count(state.premise.rawLogline)
  }

  // Series context
  if (state.premise?.seriesContext?.isSeries) {
    md.push('## SERIES CONTEXT\n')
    md.push(`**Series:** ${state.premise.seriesContext.seriesTitle}\n`)
    md.push(`**Books:** ${state.premise.seriesContext.bookCount}\n`)
    md.push(`**Overall Arc:** ${state.premise.seriesContext.overallArc || '-'}\n\n`)
  }

  // ─── PROTAGONIST ───────────────────────────────────────────────
  md.push('## PROTAGONIST\n')
  md.push(`**Name:** ${protagonist.name || '-'}\n`)
  if (protagonist.age) md.push(`**Age:** ${protagonist.age}\n`)
  if (protagonist.occupation) md.push(`**Occupation:** ${protagonist.occupation}\n`)
  md.push('\n')

  md.push('### The Five Core Elements\n')
  md.push(`| Element | Description |\n`)
  md.push(`|---------|-------------|\n`)
  md.push(`| **WANT** | ${protagonist.want || '-'} |\n`)
  md.push(`| **NEED** | ${protagonist.need || '-'} |\n`)
  md.push(`| **GHOST** | ${protagonist.ghost || '-'} |\n`)
  md.push(`| **FLAW** | ${protagonist.flaw || '-'} |\n`)
  md.push(`| **CORE LIE** | ${protagonist.coreLie || '-'} |\n`)
  md.push(`| **ARC** | ${protagonist.arcDirection || '-'} |\n`)
  md.push('\n')

  if (protagonist.dailyLife) {
    md.push(`### Ordinary World\n`)
    md.push(`${protagonist.dailyLife}\n\n`)
    count(protagonist.dailyLife)
  }

  if (protagonist.voice) {
    md.push(`### Voice\n`)
    md.push(`${protagonist.voice}\n\n`)
  }

  // ─── SUPPORTING CAST ───────────────────────────────────────────
  md.push('## SUPPORTING CAST\n')
  const characters = state.characters || []
  characters.forEach((char, i) => {
    md.push(`### ${i + 1}. ${char.name} (${char.role})\n`)
    md.push(`| | |\n`)
    md.push(`|--|--|\n`)
    md.push(`| **Want** | ${char.want || '-'} |\n`)
    md.push(`| **Need** | ${char.need || '-'} |\n`)
    md.push(`| **Flaw** | ${char.flaw || '-'} |\n`)
    md.push(`| **Ghost** | ${char.ghost || '-'} |\n`)
    md.push(`| **Arc** | ${char.arcSummary || '-'} |\n`)
    md.push(`| **Relationship** | ${char.relationshipToProtagonist || '-'} |\n`)
    md.push(`| **Enters** | ${char.meetsProtagonistAt || '-'} |\n`)
    md.push('\n')
    count(char.want)
    count(char.need)
  })

  // ─── RELATIONSHIPS ─────────────────────────────────────────────
  md.push('## RELATIONSHIP WEB\n')
  const relationships = (state.relationships || []) as Array<{
    characterA: string
    characterB: string
    connection?: string
    conflict?: string
    whatTheyWantFromEachOther?: string
  }>
  relationships.forEach(rel => {
    md.push(`**${rel.characterA} ↔ ${rel.characterB}**\n`)
    if (rel.connection) md.push(`Connection: ${rel.connection}\n`)
    if (rel.conflict) md.push(`Conflict: ${rel.conflict}\n`)
    if (rel.whatTheyWantFromEachOther) md.push(`Mutual Want: ${rel.whatTheyWantFromEachOther}\n`)
    md.push('\n')
  })

  // ─── B STORY ───────────────────────────────────────────────────
  if (bStory.character) {
    md.push('## B STORY\n')
    md.push(`**Character:** ${bStory.character as string}\n`)
    md.push(`**Premise:** ${(bStory.premise as string) || '-'}\n`)
    md.push(`**Arc:** ${(bStory.arc as string) || '-'}\n`)
    md.push(`**Theme Connection:** ${(bStory.themeConnection as string) || '-'}\n`)
    if (bStory.beats) {
      const bBeats = bStory.beats as Record<string, string>
      md.push(`\n**Beats:**\n`)
      md.push(`- Begins: ${bBeats.begins || '-'}\n`)
      md.push(`- Deepens: ${bBeats.deepens || '-'}\n`)
      md.push(`- Resolves: ${bBeats.resolves || '-'}\n`)
    }
    md.push('\n')
  }

  // ─── SUBPLOTS ──────────────────────────────────────────────────
  if (subplots.length > 0) {
    md.push('## SUBPLOTS\n')
    subplots.forEach((sp, i) => {
      md.push(`### ${i + 1}. ${sp.name} (${sp.character})\n`)
      md.push(`**Purpose:** ${sp.purpose || '-'}\n`)
      md.push(`**Premise:** ${sp.premise || '-'}\n`)
      if (sp.beats) {
        md.push(`\n- Setup: ${sp.beats.setup || '-'}\n`)
        md.push(`- Complication: ${sp.beats.complication || '-'}\n`)
        md.push(`- Resolution: ${sp.beats.resolution || '-'}\n`)
      }
      md.push('\n')
    })
  }

  // ─── BEAT SHEET ────────────────────────────────────────────────
  md.push('## BEAT SHEET\n')
  const beats = (beatSheet.beats || {}) as Record<string, Record<string, string | null>>
  const beatOrder = [
    { id: 'beat01OpeningImage', name: 'Opening Image' },
    { id: 'beat02Setup', name: 'Setup' },
    { id: 'beat03Catalyst', name: 'Catalyst' },
    { id: 'beat04Debate', name: 'Debate' },
    { id: 'beat05BreakIntoTwo', name: 'Break Into Two' },
    { id: 'beat06BStory', name: 'B Story' },
    { id: 'beat07FunAndGames', name: 'Fun and Games' },
    { id: 'beat08Midpoint', name: 'Midpoint' },
    { id: 'beat09BadGuysCloseIn', name: 'Bad Guys Close In' },
    { id: 'beat10AllIsLost', name: 'All Is Lost' },
    { id: 'beat11BlackMoment', name: 'Black Moment' },
    { id: 'beat12Beat13', name: 'Break Into Three' },
    { id: 'beat13Finale', name: 'Finale' },
    { id: 'beat14FinalImage', name: 'Final Image' },
    { id: 'beat15EndCredits', name: 'End Credits' },
  ]

  beatOrder.forEach(b => {
    const beat = beats[b.id] || {}
    md.push(`### ${b.name}\n`)
    if (beat.scene) md.push(`**Scene:** ${beat.scene}\n`)
    if (beat.image) md.push(`**Image:** ${beat.image}\n`)
    if (beat.notes) md.push(`**Notes:** ${beat.notes}\n`)
    if (b.id === 'beat08Midpoint' && beat.midpointType) {
      md.push(`**Type:** ${beat.midpointType === 'falseVictory' ? 'False Victory' : 'False Defeat'}\n`)
      if (beat.flipOrReveal) md.push(`**Flip/Reveal:** ${beat.flipOrReveal}\n`)
    }
    if (b.id === 'beat10AllIsLost' && beat.whiffOfDeath) {
      md.push(`**Whiff of Death:** ${beat.whiffOfDeath}\n`)
    }
    if (b.id === 'beat13Finale') {
      if (beat.selfRevelation) md.push(`**Self-Revelation:** ${beat.selfRevelation}\n`)
      if (beat.newEquilibrium) md.push(`**New Equilibrium:** ${beat.newEquilibrium}\n`)
    }
    md.push('\n')
    count(beat.scene)
  })

  // ─── SCENE OUTLINE ─────────────────────────────────────────────
  md.push('## CHAPTER OUTLINE\n')
  chapters.forEach(ch => {
    md.push(`### Chapter ${ch.chapterNumber}: ${ch.chapterTitle}\n`)
    if (ch.beat) md.push(`*Beat: ${ch.beat}*\n\n`)
    ch.scenes.forEach(sc => {
      md.push(`#### Scene ${sc.sceneNumber}\n`)
      md.push(`| Field | Value |\n`)
      md.push(`|-------|-------|\n`)
      md.push(`| **Location** | ${sc.location || '-'} |\n`)
      md.push(`| **Time** | ${sc.timeOfDay || '-'} |\n`)
      md.push(`| **POV** | ${sc.pov || '-'} |\n`)
      md.push(`| **Summary** | ${sc.summary || '-'} |\n`)
      md.push(`| **Purpose** | ${sc.purpose || '-'} |\n`)
      md.push(`| **Conflict** | ${sc.conflict || '-'} |\n`)
      md.push(`| **What Changes** | ${sc.whatChanges || '-'} |\n`)
      md.push(`| **Serves** | ${sc.beats || '-'} |\n`)
      md.push('\n')
      count(sc.summary)
    })
  })

  // ─── PLOT THREADS ─────────────────────────────────────────────
  md.push('## PLOT THREAD REGISTRY\n')
  md.push(`| Thread | Type | Status | Resolution |\n`)
  md.push(`|--------|------|--------|------------|\n`)
  threads.forEach(t => {
    md.push(`| ${t.name} | ${t.type} | ${t.status} | ${t.resolutionPlan || '-'} |\n`)
  })
  md.push('\n')

  // ─── WORD COUNT ESTIMATE ───────────────────────────────────────
  const estimatedChapters = chapters.length
  const avgWordsPerChapter = genre.targetWordCount
    ? Math.round(genre.targetWordCount / Math.max(estimatedChapters, 1))
    : 2500

  md.push('---\n')
  md.push('## METADATA\n')
  md.push(`- **Estimated Chapters:** ${estimatedChapters}\n`)
  md.push(`- **Avg Words/Chapter:** ${avgWordsPerChapter.toLocaleString()}\n`)
  md.push(`- **Plot Threads:** ${threads.length}\n`)
  md.push(`- **Subplots:** ${subplots.length}\n`)
  md.push(`- **Supporting Characters:** ${characters.length}\n`)
  md.push(`- **Generated:** ${new Date().toISOString()}\n`)

  const filePath = path.resolve(outputDir, 'master-document.md')
  await fsPromises.writeFile(filePath, md.join(''))

  return {
    path: filePath,
    wordCount: genre.targetWordCount || 80000,
    chapterCount: chapters.length,
    beatCount: 15,
    threadCount: threads.length,
  }
}
