// NF-11.5 — NF master document generator.
//
// Generates output/nf-master-document.md from the normalized WritingPlan.
// Covers DNA (title, promise, transformation, audience), author angle,
// voice/tone, evidence philosophy, commercial model, chapter outline,
// and research summary. Triggered after pa-master / pb-master / pc-master saves.

import * as fs from 'fs'
import * as path from 'path'
import type { WritingPlan } from '../state/writing-plan.js'
import type { ProjectState } from '../state/project-state.js'

export interface NfMasterDocResult {
  outputPath: string
  chapterCount: number
  researchItemCount: number
}

function field(label: string, value: string | null | undefined): string {
  if (!value) return ''
  return `**${label}:** ${value}  \n`
}

function section(title: string, content: string): string {
  if (!content.trim()) return ''
  return `## ${title}\n\n${content}\n`
}

export function generateNfMasterDocument(
  plan: WritingPlan,
  state: ProjectState,
  projectDir: string,
): NfMasterDocResult {
  const outputDir = path.join(projectDir, 'output')
  fs.mkdirSync(outputDir, { recursive: true })

  const outputPath = path.join(outputDir, 'nf-master-document.md')
  const title = plan.title ?? 'Untitled'
  const nf = (state.nfStages ?? {}) as Record<string, Record<string, unknown>>
  const top = state as unknown as Record<string, Record<string, unknown>>

  function stage(key: string): Record<string, unknown> {
    return (nf[key] ?? top[key] ?? {}) as Record<string, unknown>
  }

  function str(v: unknown): string | null {
    return typeof v === 'string' && v ? v : null
  }

  const lines: string[] = [
    `# ${title}`,
    '',
    `*Non-Fiction Planning Document — Generated by Storyline*`,
    `*Generated: ${new Date().toISOString().split('T')[0]} · Pipeline: ${plan.pipeline ?? 'A'}*`,
    '',
    '---',
    '',
  ]

  // ── Book DNA ───────────────────────────────────────────────────────────────
  const category   = stage('dna-category')
  const reader     = stage('dna-reader')
  const transform  = stage('dna-transform')
  const promise    = stage('dna-promise')
  const author     = stage('dna-author')
  const voice      = stage('dna-voice')
  const evidence   = stage('dna-evidence')
  const commercial = stage('dna-commercial')
  const titleStage = stage('dna-title')

  let dnaBlock = ''
  dnaBlock += field('Category', str(category.primaryCategory ?? category.category))
  dnaBlock += field('Audience', str(reader.readerDescription ?? category.audience ?? plan.audience))
  dnaBlock += field('Core promise', str(promise.corePromise ?? (plan.nfPromise?.corePromise)))
  dnaBlock += field('Subtitle', str(promise.subtitleDraft ?? (plan.nfPromise?.subtitleDraft) ?? titleStage.workingTitle))
  dnaBlock += field('Reader before state', str(transform.beforeState))
  dnaBlock += field('Reader after state', str(transform.afterState))
  if (dnaBlock) lines.push(...section('Book DNA', dnaBlock).split('\n'))

  let authorBlock = ''
  authorBlock += field('Author angle', str(author.authorAngle))
  authorBlock += field('Credibility', str(author.credibility))
  if (authorBlock) lines.push(...section('Author Angle', authorBlock).split('\n'))

  let voiceBlock = ''
  voiceBlock += field('Voice', str(voice.voice))
  voiceBlock += field('Tone', str(voice.tone))
  voiceBlock += field('Style notes', str(voice.styleNotes))
  if (voiceBlock) lines.push(...section('Voice & Tone', voiceBlock).split('\n'))

  let evidenceBlock = ''
  evidenceBlock += field('Evidence approach', str(evidence.evidenceApproach))
  evidenceBlock += field('Primary sources', str(evidence.primarySources))
  if (evidenceBlock) lines.push(...section('Evidence Philosophy', evidenceBlock).split('\n'))

  let commercialBlock = ''
  commercialBlock += field('Revenue model', str(commercial.revenueModel))
  commercialBlock += field('Distribution', str(commercial.distribution))
  if (commercialBlock) lines.push(...section('Commercial Model', commercialBlock).split('\n'))

  // ── Pipeline-specific framework (Pipeline A only) ─────────────────────────
  if (plan.pipeline === 'A') {
    const thesis    = stage('pa-thesis')
    const framework = stage('pa-framework')
    let frameworkBlock = ''
    frameworkBlock += field('Thesis', str(thesis.thesis))
    frameworkBlock += field('Framework', str(framework.modelName ?? framework.frameworkDescription))
    if (Array.isArray(framework.steps) && framework.steps.length > 0) {
      frameworkBlock += '\n**Steps:**\n'
      for (const s of framework.steps) frameworkBlock += `- ${s}\n`
    }
    if (Array.isArray(framework.principles) && framework.principles.length > 0) {
      frameworkBlock += '\n**Principles:**\n'
      for (const p of framework.principles) frameworkBlock += `- ${p}\n`
    }
    if (frameworkBlock) lines.push(...section('Framework', frameworkBlock).split('\n'))
  }

  // ── Chapter outline ────────────────────────────────────────────────────────
  if (plan.nfChapters.length > 0) {
    lines.push('## Chapter Outline', '')
    for (const ch of plan.nfChapters) {
      const num = ch.number ?? '?'
      const chTitle = ch.title ?? `Chapter ${num}`
      lines.push(`### Chapter ${num} — ${chTitle}`, '')
      if (ch.mission ?? ch.linkedPrinciple ?? ch.chapterQuestion ?? ch.learningObjective) {
        if (ch.mission)           lines.push(field('Mission', ch.mission).trimEnd())
        if (ch.linkedPrinciple)   lines.push(field('Principle', ch.linkedPrinciple).trimEnd())
        if (ch.chapterQuestion)   lines.push(field('Question', ch.chapterQuestion).trimEnd())
        if (ch.learningObjective) lines.push(field('Objective', ch.learningObjective).trimEnd())
      }
      if (ch.wordCountEstimate) lines.push(field('Target words', `~${Number(ch.wordCountEstimate).toLocaleString()}`).trimEnd())
      if (ch.sections.length > 0) {
        lines.push('', `**Sections:** ${ch.sections.map(s => s.title).join(' · ')}`)
      }
      lines.push('')
    }
  }

  // ── Research summary ───────────────────────────────────────────────────────
  const researchItems = plan.researchItems.filter(r => r.status !== 'cited')
  if (researchItems.length > 0) {
    lines.push('## Research Required', '')
    for (const r of researchItems) {
      const loc = r.chapterNumber != null ? ` *(Ch ${r.chapterNumber})*` : ''
      lines.push(`- [ ] ${r.description}${loc}`)
    }
    lines.push('')
  }

  lines.push(
    '---',
    `*Storyline NF Master Document — updated on every master-stage save.*`,
  )

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

  return {
    outputPath,
    chapterCount: plan.nfChapters.length,
    researchItemCount: researchItems.length,
  }
}
