// NF-11.7 — Research-todo register.
//
// Generates output/research-todo.md from the WritingPlan's researchItems,
// grouped by chapter and section, with status tags.
// Loose items (no chapter assignment) appear in a tail section.
// Refreshed after chapter-plan and evidence stage saves.

import * as fs from 'fs'
import * as path from 'path'
import type { WritingPlan, ResearchTodoItem } from '../state/writing-plan.js'

export interface ResearchTodoResult {
  outputPath: string
  totalItems: number
  pendingCount: number
}

const STATUS_BADGE: Record<ResearchTodoItem['status'], string> = {
  planned:  '⬜',
  captured: '🟡',
  verified: '🟢',
  cited:    '✅',
}

function renderItem(r: ResearchTodoItem): string {
  const badge = STATUS_BADGE[r.status] ?? '⬜'
  const scene = r.sceneNumber != null ? `, Scene ${r.sceneNumber}` : ''
  const loc = r.chapterNumber != null ? ` *(Ch ${r.chapterNumber}${scene})*` : ''
  return `- ${badge} ${r.description}${loc}`
}

export function generateResearchTodo(plan: WritingPlan, projectDir: string): ResearchTodoResult {
  const outputDir = path.join(projectDir, 'output')
  fs.mkdirSync(outputDir, { recursive: true })

  const outputPath = path.join(outputDir, 'research-todo.md')
  const title = plan.title ?? 'Untitled'
  const all = plan.researchItems

  const pending = all.filter(r => r.status === 'planned' || r.status === 'captured')

  const lines: string[] = [
    `# Research Todo — ${title}`,
    '',
    `*Auto-generated by Storyline — edits will be overwritten on next save.*`,
    `*Generated: ${new Date().toISOString().split('T')[0]}*`,
    `*${all.length} item${all.length !== 1 ? 's' : ''} tracked · ${pending.length} pending*`,
    '',
  ]

  if (all.length === 0) {
    lines.push(
      '*No research items found. Complete the chapter-plan and evidence stages to populate this register.*',
      '',
    )
  } else {
    // Group by chapter number
    const byChapter = new Map<number, ResearchTodoItem[]>()
    const loose: ResearchTodoItem[] = []

    for (const r of all) {
      if (r.chapterNumber != null) {
        if (!byChapter.has(r.chapterNumber)) byChapter.set(r.chapterNumber, [])
        byChapter.get(r.chapterNumber)!.push(r)
      } else {
        loose.push(r)
      }
    }

    // Render chapter groups in order
    const sortedChapters = [...byChapter.keys()].sort((a, b) => a - b)
    for (const chNum of sortedChapters) {
      const items = byChapter.get(chNum)!
      const chTitle = plan.nfChapters.find(c => c.number === chNum)?.title
        ?? plan.fictionChapters.find(c => c.chapterNumber === chNum)?.chapterTitle
        ?? null
      const heading = chTitle ? `Chapter ${chNum} — ${chTitle}` : `Chapter ${chNum}`
      lines.push(`## ${heading}`, '')
      for (const r of items) lines.push(renderItem(r))
      lines.push('')
    }

    // Loose items tail
    if (loose.length > 0) {
      lines.push('## General Research', '')
      for (const r of loose) lines.push(renderItem(r))
      lines.push('')
    }
  }

  lines.push(
    '---',
    '*Storyline Research Todo — updated on every chapter-plan or evidence-map save.*',
  )

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

  return {
    outputPath,
    totalItems: all.length,
    pendingCount: pending.length,
  }
}
