// FIC-D.2 — Story-bible renderer.
//
// Derives `output/story-bible.md` from the normalized WritingPlan.
// Skips empty sections; never prints "(none)" placeholders.
// Refreshed after saves to characters, relationships, chapterOutline, beatSheet.

import * as fs from 'fs'
import * as path from 'path'
import type { WritingPlan, FictionCharacter } from '../state/writing-plan.js'

export interface StoryBibleResult {
  outputPath: string
  characterCount: number
  locationCount: number
}

export function generateStoryBible(plan: WritingPlan, projectDir: string): StoryBibleResult {
  const outputDir = path.join(projectDir, 'planning')
  fs.mkdirSync(outputDir, { recursive: true })

  const outputPath = path.join(outputDir, 'story-bible.md')
  const title = plan.title ?? 'Untitled'

  const lines: string[] = [
    `# Story Bible — ${title}`,
    '',
    `*Auto-generated by Storyline — edits will be overwritten on next save.*`,
    `*Generated: ${new Date().toISOString().split('T')[0]}*`,
    '',
  ]

  const allChars: FictionCharacter[] = [
    ...(plan.protagonist ? [plan.protagonist] : []),
    ...plan.cast,
  ]

  if (allChars.length > 0) {
    lines.push('## Cast', '')
    for (const char of allChars) {
      const roleLabel = char.isProtagonist ? 'protagonist' : (char.role ?? null)
      lines.push(`### ${char.name}${roleLabel ? ` *(${roleLabel})*` : ''}`, '')
      const fields: [string, string | null | undefined][] = [
        ['Want', char.want],
        ['Need', char.need],
        ['Lie', char.coreLie],
        ['Wound', char.ghost],
        ['Flaw', char.flaw],
        ['Arc', char.arcDirection ?? char.arcSummary],
      ]
      let hasField = false
      for (const [label, value] of fields) {
        if (value) {
          lines.push(`**${label}:** ${value}  `)
          hasField = true
        }
      }
      if (!hasField) lines.push('*No arc data captured yet.*  ')
      lines.push('')
    }
  }

  if (plan.relationships.length > 0) {
    lines.push('## Relationships', '')
    for (const rel of plan.relationships) {
      lines.push(`### ${rel.characterA} ↔ ${rel.characterB}`, '')
      if (rel.connection) lines.push(`**Connection:** ${rel.connection}  `)
      if (rel.conflict) lines.push(`**Conflict:** ${rel.conflict}  `)
      if (rel.whatTheyWantFromEachOther) lines.push(`**What they want from each other:** ${rel.whatTheyWantFromEachOther}  `)
      lines.push('')
    }
  }

  const locations = plan.storyBible?.locations ?? []
  if (locations.length > 0) {
    lines.push('## Locations', '')
    for (const loc of locations) {
      const chapList = loc.chapters.map(c => `Ch ${c}`).join(', ')
      lines.push(`- **${loc.name}** — ${chapList}`)
    }
    lines.push('')
  }

  const recurringObjects = plan.storyBible?.recurringObjects ?? []
  if (recurringObjects.length > 0) {
    lines.push('## Recurring Objects', '')
    for (const obj of recurringObjects) {
      lines.push(`- **${obj.name}**${obj.notes ? ` — ${obj.notes}` : ''}`)
    }
    lines.push('')
  }

  const continuityFacts = plan.storyBible?.continuityFacts ?? []
  lines.push('## Continuity Facts', '')
  if (continuityFacts.length > 0) {
    for (const fact of continuityFacts) {
      lines.push(`- ${fact.fact}${fact.chapter ? ` *(Ch ${fact.chapter})*` : ''}`)
    }
  } else {
    lines.push('*Continuity facts grow as you draft — add them here to track details that need to stay consistent.*')
  }
  lines.push('')

  lines.push(
    '---',
    '*Storyline Story Bible — updated on every cast, relationship, or chapter save.*',
  )

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

  return {
    outputPath,
    characterCount: allChars.length,
    locationCount: locations.length,
  }
}
