// CB-11 — File-system watcher for planning/stages/*.md.
//
// Stage docs are derived data: the renderer in @storyline/core writes
// them after every successful stage save. Users sometimes edit them
// by hand, expecting their changes to flow back into state.json — but
// they don't. The next save overwrites the file. The user's edits are
// lost silently.
//
// This module watches the directory and:
//   1. Suppresses self-writes (Storyline's own writeStageDoc → fs change
//      → ignore). Suppression is path-scoped + time-windowed.
//   2. On a real user edit, shows a one-time per-session toast:
//      "Stage docs are auto-generated. Edits will be overwritten on the
//      next save. Use the chat to update <stageId> permanently."
//   3. Provides a reset command (storyline.resetStageDoc) that
//      regenerates the file from state.json — restoring it after the
//      user has accidentally overwritten it.
//
// Round-trip parsing (turning user edits in the .md back into a
// state-patch) is intentionally not in this MVP. It needs a
// label-to-key map per stage, and lossy / opaque renderer patterns
// (tables, nested lists) make it brittle. Tracked as CB-11b.

import * as vscode from 'vscode'
import * as path from 'path'
import { writeStageDoc, stageOrderFor } from '@storyline/core'
import { LocalStore } from './local-store.js'
import { logInfo, logWarn } from '../diagnostic-log.js'

const SUPPRESSION_WINDOW_MS = 2_000
const NOTIFIED_KEY = 'storyline.stageMdEditNotified'

/**
 * Paths we just wrote ourselves — fs change events for these paths
 * within SUPPRESSION_WINDOW_MS are ignored. Without this, every
 * `writeStageDoc` call would trigger our own change handler.
 *
 * Exported so ChatPanel + other writers can call markSelfWrite() right
 * after their writeStageDoc call.
 */
const recentSelfWrites = new Map<string, number>()

export function markStageDocSelfWrite(absolutePath: string): void {
  recentSelfWrites.set(absolutePath, Date.now())
  // Trim ageing entries on every set — the map stays small.
  for (const [p, t] of recentSelfWrites) {
    if (Date.now() - t > SUPPRESSION_WINDOW_MS * 2) recentSelfWrites.delete(p)
  }
}

function isSelfWrite(absolutePath: string): boolean {
  const t = recentSelfWrites.get(absolutePath)
  if (t === undefined) return false
  return Date.now() - t < SUPPRESSION_WINDOW_MS
}

/**
 * Wire the watcher into the extension lifecycle. Called once from
 * activate() — only when the workspace has a Storyline project, since
 * non-project workspaces don't have stages/.
 */
export function registerStageMdWatcher(context: vscode.ExtensionContext): void {
  const folder = vscode.workspace.workspaceFolders?.[0]
  if (!folder) return

  // Glob is workspace-scoped so it only fires on the active project's
  // stage docs, not arbitrary stages/ directories elsewhere on disk.
  const pattern = new vscode.RelativePattern(folder, 'planning/stages/*.md')
  const watcher = vscode.workspace.createFileSystemWatcher(pattern)

  const handle = (uri: vscode.Uri): void => {
    if (isSelfWrite(uri.fsPath)) return
    const stageId = path.basename(uri.fsPath, '.md')
    logInfo(`[Storyline] stage-md-watcher: user edit detected on ${stageId}.md`)
    void notifyOncePerSession(context, stageId)
  }

  context.subscriptions.push(watcher.onDidChange(handle))
  context.subscriptions.push(watcher)
  logInfo('[Storyline] stage-md-watcher: registered for planning/stages/*.md')
}

async function notifyOncePerSession(
  context: vscode.ExtensionContext,
  stageId: string,
): Promise<void> {
  // Per-session: workspaceState lives until the workspace closes. Users
  // who repeatedly edit stage docs across sessions get re-warned, which
  // is the right balance — once-ever is too quiet, every edit is noise.
  if (context.workspaceState.get<boolean>(NOTIFIED_KEY) === true) return
  await context.workspaceState.update(NOTIFIED_KEY, true)

  const choice = await vscode.window.showInformationMessage(
    `You edited planning/stages/${stageId}.md. Stage docs are auto-generated by Storyline — manual edits are overwritten on the next save. To update this stage permanently, ask in the planning chat.`,
    'Open chat',
    'Reset stage doc',
    'Got it',
  )
  if (choice === 'Open chat') {
    void vscode.commands.executeCommand('storyline.openPlanning')
  } else if (choice === 'Reset stage doc') {
    void vscode.commands.executeCommand('storyline.resetStageDoc', stageId)
  }
}

/**
 * Regenerate planning/stages/<stageId>.md from current state.json.
 * Bound to the storyline.resetStageDoc command, also available as a
 * Files tree context-menu action.
 */
export async function resetStageDoc(stageIdHint?: string): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath
  if (!folder) return
  const store = LocalStore.fromWorkspace()
  if (!store) return

  // If no stage hint was passed (e.g. command invoked from the palette),
  // ask which stage. Pull the list from the active state.json's
  // completed stages — only those have a doc to reset.
  let stageId = stageIdHint
  if (!stageId) {
    const state = await store.read()
    const completed = Object.keys(state.stages ?? {}).filter(id => state.stages?.[id]?.completed)
    if (completed.length === 0) {
      void vscode.window.showInformationMessage('No completed stages yet — nothing to reset.')
      return
    }
    stageId = await vscode.window.showQuickPick(completed, {
      title: 'Reset which stage doc?',
      placeHolder: 'Pick the stage whose .md to regenerate from state.json',
    })
    if (!stageId) return
  }

  try {
    const state = await store.read()
    const written = await writeStageDoc(stageId, state, folder)
    if (written) {
      markStageDocSelfWrite(written)
      void vscode.window.showInformationMessage(`Regenerated planning/stages/${stageId}.md from state.`)
    } else {
      void vscode.window.showWarningMessage(`No data captured for stage "${stageId}" yet — nothing to write.`)
    }
  } catch (err) {
    logWarn('[Storyline] resetStageDoc failed:', err)
    void vscode.window.showErrorMessage(`Couldn't reset stage doc: ${err instanceof Error ? err.message : String(err)}`)
  }
}

/**
 * Walk the active mode/pipeline's stage order and write planning/stages/<id>.md
 * for every stage that has captured data in state.json. Stages without data
 * are skipped (writeStageDoc returns null). Used to repair a project where
 * stage MDs went missing — earlier writeStageDoc only fired during the AI
 * save path and silently no-op'd for stages without bespoke renderers.
 *
 * Reports a summary toast: how many were written, how many had no data,
 * how many failed.
 */
export async function backfillAllStageDocs(): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath
  if (!folder) {
    void vscode.window.showWarningMessage('Open a Storyline project before backfilling stage docs.')
    return
  }
  const store = LocalStore.fromWorkspace()
  if (!store) {
    void vscode.window.showWarningMessage('No .storyline/state.json found in this workspace.')
    return
  }

  let state: Awaited<ReturnType<typeof store.read>>
  try {
    state = await store.read()
  } catch (err) {
    logWarn('[Storyline] backfillAllStageDocs: failed to read state', err)
    void vscode.window.showErrorMessage(`Couldn't read state.json: ${err instanceof Error ? err.message : String(err)}`)
    return
  }

  const order = stageOrderFor(state)
  let wrote = 0
  let skipped = 0
  let failed = 0
  const failures: string[] = []

  for (const stage of order) {
    try {
      const written = await writeStageDoc(stage.id, state, folder)
      if (written) {
        markStageDocSelfWrite(written)
        wrote++
      } else {
        skipped++
      }
    } catch (err) {
      failed++
      failures.push(stage.id)
      logWarn(`[Storyline] backfill: writeStageDoc failed for ${stage.id}`, err)
    }
  }

  logInfo(`[Storyline] backfillAllStageDocs: wrote=${wrote} skipped=${skipped} failed=${failed}`)
  const summary = `Stage docs backfilled — ${wrote} written, ${skipped} skipped (no data), ${failed} failed${failures.length ? ` (${failures.join(', ')})` : ''}.`
  if (failed > 0) {
    void vscode.window.showWarningMessage(summary)
  } else {
    void vscode.window.showInformationMessage(summary)
  }
}
